// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BookStore.Migrations
{
    [DbContext(typeof(BookCategoryContext))]
    partial class BookCategoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BookStore.Models.BookCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("book_categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cb0457d-eab1-46ac-a312-cbd720b0c3f4"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 103, DateTimeKind.Local).AddTicks(9960),
                            Name = "Data"
                        },
                        new
                        {
                            Id = new Guid("ef4c4a26-d971-449d-8472-116923809099"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7020),
                            Name = "Development"
                        },
                        new
                        {
                            Id = new Guid("b2ceac0a-b821-48ec-bc05-b6477e26f83d"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7040),
                            Name = "General"
                        },
                        new
                        {
                            Id = new Guid("68bfd1fd-fc14-4c3e-aa15-d11592a08423"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7040),
                            Name = "Java/JVM"
                        },
                        new
                        {
                            Id = new Guid("f6d724ad-a480-4205-b11a-7ca689633316"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7050),
                            Name = "Microsoft &.NET"
                        },
                        new
                        {
                            Id = new Guid("ec378350-cd7c-4226-9fd3-2ccbec4b143e"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7050),
                            Name = "Operations & Cloud"
                        },
                        new
                        {
                            Id = new Guid("bf13e0cc-5a93-403d-bf6b-b2471c69bf69"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7050),
                            Name = "Programming"
                        },
                        new
                        {
                            Id = new Guid("0beb0a26-fd92-48d4-8cbf-9f18a839481a"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7060),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("85582997-4b6e-4689-93d4-329046df91df"),
                            CreatedAt = new DateTime(2021, 11, 27, 17, 47, 18, 111, DateTimeKind.Local).AddTicks(7060),
                            Name = "Web"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
